name: "Deploy ARC Scale Set (Orchestrator)"
description: "Write CA cert, ensure namespace/configmap, then helm deploy a scale set"
inputs:
  installation_name:
    required: true
  namespace:
    required: true
  github_config_url:
    required: true
  cm_name:
    required: true
  runner_image:
    required: true
  chart_path:
    required: true

runs:
  using: "composite"
  steps:
    - uses: SecurityUniversalOrg/ghe-actions/actions/gha-write-ghes-ca-cert@v1

    - uses: SecurityUniversalOrg/ghe-actions/actions/gha-ensure-namespace-and-ca-configmap@v1
      with:
        namespace: ${{ inputs.namespace }}
        cm_name: ${{ inputs.cm_name }}

    - uses: SecurityUniversalOrg/ghe-actions/actions/gha-helm-deploy-arc-scaleset@v1
      with:
        installation_name: ${{ inputs.installation_name }}
        namespace: ${{ inputs.namespace }}
        github_config_url: ${{ inputs.github_config_url }}
        cm_name: ${{ inputs.cm_name }}
        runner_image: ${{ inputs.runner_image }}
        chart_path: ${{ inputs.chart_path }}