name: "Generate Container SBOM"
description: "Generate a Docker Container SBOM using SPDX or CycloneDX"
inputs:
  primary_ref: { required: true }

runs:
  using: "composite"
  steps:
    - id: generate-sbom
      shell: bash
      env:
        PRIMARY_FULL_IMAGE_REF: ${{ inputs.primary_ref }}
      run: |
        set -euo pipefail

        FULL_REF="${PRIMARY_FULL_IMAGE_REF}"

        # Generate SPDX JSON SBOM (write directly to file)
        syft "registry:${FULL_REF}" -o spdx-json=sbom.spdx.json

        # Validate it's actually JSON
        jq -e . sbom.spdx.json >/dev/null

        # Attach as an attestation (SPDX JSON)
        cosign attest --type spdxjson --predicate sbom.spdx.json "${FULL_REF}"