name: "Install kubectl"
description: "Install kubectl CLI"
runs:
  using: "composite"
  steps:
    - name: Install kubectl
      shell: bash
      run: |
        set -euo pipefail
        curl -sSL -o kubectl "https://dl.k8s.io/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/kubectl
        kubectl version --client