name: "Get Kubeconfig (Orchestrator)"
description: "Install tooling + auth + produce kubeconfig for AKS/EKS"
inputs:
  cloud:
    description: "azure|aws"
    required: true
  cluster_name:
    required: true
  cluster_resource_group:
    required: false
  aws_region:
    required: false

runs:
  using: "composite"
  steps:
    - uses: SecurityUniversalOrg/ghe-actions/actions/k8-install-kubectl@v1
    - uses: SecurityUniversalOrg/ghe-actions/actions/helm-install-helm@v1

    # Azure
    - name: Azure login
      if: ${{ inputs.cloud == 'azure' }}
      uses: SecurityUniversalOrg/ghe-actions/actions/cloud-auth-azure@v1

    - name: AKS kubeconfig
      if: ${{ inputs.cloud == 'azure' }}
      uses: SecurityUniversalOrg/ghe-actions/actions/k8-aks-get-kubeconfig@v1
      with:
        cluster_name: ${{ inputs.cluster_name }}
        cluster_resource_group: ${{ inputs.cluster_resource_group }}
        admin: "true"

    # AWS
    - name: AWS configure creds
      if: ${{ inputs.cloud == 'aws' }}
      uses: SecurityUniversalOrg/ghe-actions/actions/cloud-auth-aws@v1
      with:
        aws_region: ${{ inputs.aws_region }}

    - name: EKS kubeconfig
      if: ${{ inputs.cloud == 'aws' }}
      uses: SecurityUniversalOrg/ghe-actions/actions/k8-eks-get-kubeconfig@v1
      with:
        cluster_name: ${{ inputs.cluster_name }}
        aws_region: ${{ inputs.aws_region }}